### ISSUE TITLE
Missing Method

### ISSUE THREAD

**Issue by norwynn** [ayayalar/DotNetRuleEngine#3]
Hello,

What would cause this error?

```
System.MissingMethodException: Method not found: 'DotNetRuleEngine.Core.RuleEngine`1<!0> DotNetRuleEngine.Core.RuleEngine`1.GetInstance(!0, DotNetRuleEngine.Core.Interface.IDependencyResolver)'.
    at ProcessRules(ITestRule testRule)
```

I was able to create and run unit tests using version 3.0 of the rule engine library on my local dev machine.  Problem is i get that error when the tests are run on my CI server.  Anything i missed?  Dependencies I need to check?

Thanks!

**Comment by ayayalar** [comment]
Hello,

I would need little bit more information but it looks like you don't have an implementation of IDependencyResolver but you are still trying to use it. Could you send me how are you constructing the RuleEngine?

**Comment by norwynn** [comment]
I was following/copying the unit tests as well as the examples in the wiki.  This is the code for creating the engine.  Method is called depending on type of rule name/type.

```
private IRuleResult ProcessSomeRule(ISomeRuleData someRuleData)
{
    var engine = RuleEngine<someReportRuleData>.GetInstance(someRuleData as someReportRuleData);
    engine.ApplyRules(new SomeRule());
    var result = engine.Execute().FindRuleResult("SomeRule");

    return result;
}
```

**Comment by ayayalar** [comment]
I wonder if FindRuleResult having trouble finding the name you are passing. If you are overriding the rule name (that is in the rule result you specify the name of the rule with the Name property) otherwise you should use FindRuleResult<T>() overload. Have you looked at the wiki page for extensions? I have quite of a few examples.

**Comment by ayayalar** [comment]
In the comment I meant the FindRuleResult generic extension.

**Comment by ayayalar** [comment]
Also one more thing I've noticed you are casting ISomeRuleData to ReportData. I hope that's not passing it as null.

**Comment by norwynn** [comment]
The code I showed are part of a set of unit tests, so im pretty sure no null values are passed.  BUT, i think I figured it out.  Looks like the CI got confused with the versions.  There were 2 test projects, and one of them was referencing a very old version of the dotnetruleengine (1.xxxx) while the new one as 3.0.  So i removed the old project from the CI build/test step and the missing method error was resolved.

**Comment by ayayalar** [comment]
Awesome! Glad you figured it out.

**Comment by norwynn** [comment]
Not related to the initial question, but i'll ask anyway.  Just can't wrap my head around it.  How do I get the ruleResult of the nested rule(s)?  how is ruleResult assigned a value? 

From the sample:
```
public class QualifiesForFreeShipping: Rule<Order>
{   
    public override void Initialize()
    {
        // Nested rule(s) will run before the rule itself executed.
        Configuration.InvokeNestedRulesFirst = true; // default is false

        // Add nested rule(s)
        AddRules(new AmountGreaterThan50Dollars());
    }

    public override IRuleResult Invoke() => 
        new RuleResult { Result = ruleResult };        
}
```

**Comment by ayayalar** [comment]
For the nested rules or any type of rule, you just need to return a rule result (e.g. return new RuleResult { }). The rule engine takes all rules/nested rules flattens them into a list of rule results. So when you get the array of rule results from the rule engine execute/executeAsync call, you have all results collected into a single list of rule results.

**Comment by norwynn** [comment]
Yes, I understand that I can access the ruleresult of all rules, nested or not after rule engine execution.  What I forgot to mention in my earlier question was, how do I access the ruleresult of the child rules while still inside the parent rule?  Like the sample i pasted above, how can _QualifiesForFreeShipping_ access the ruleresult of _AmountGreaterThan50Dollars_ so that maybe I can use it for the parent rule? 

What I did at the moment was use TryAdd and TryGetValue.  In case i missed something and there is an easier way to do it.

Thanks by the way.  I'm sorry, I don't mean to bug (or be dense) LOL.  Great library, having fun using it.

**Comment by ayayalar** [comment]
No you are not bugging me at all. I am currently in Europe so due to time difference my answers might be delayed. So I apologize for that. So rule results are great way to return back artifacts (e.g. You can store exceptions, etc.) after the execution. But not for sharing data. TryAdd/TryGet meant for that exact purpose. Sharing data. So that is the correct usage. However there is another way. You can create a Context object. Then include your model inside the context object but also use context object to pass/share data among the rules. Example, in the nested rule you can store some piece of data in the context object and get it from the parent rule or any other rule. They are all aware of the context object. I hope I was clear.

Example:

class Context
{
    public Model Model {get; set;}
    public  List<string> ShareMe {get; set;}
    // put whatever you want in the context object
}


The rules should not be aware/dependent to each other. The model/context should be the

**Comment by norwynn** [comment]
Hah!  I was too focused on the RuleResult not realizing i can substitute some other class to hold the Model and other objects.  I feel so dumb LOL.  Thank you Arif for the help!

**Comment by ayayalar** [comment]
No problem at all!. Glad I could help.

Cheers
